---
title: "Process data"
author: "Ian Hussey^[Ghent University. Email: ian.hussey@ugent.be]"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE,
                      cache.lazy=FALSE)
```

```{r}
# process data

# author: Ian Hussey (ian.hussey@ugent.be)
# license: GPLv3+

# Notes:
# ProlificCode is used only to pay participants and must be deleted from 
# all data files before raw data is posted online
 

# Dependencies ------------------------------------------------------------


library(plyr)
library(tidyverse)
library(data.table)
library(schoRsch)


# Data acquisition and cleaning -------------------------------------------


# set the working directory
setwd("processed")

# get screened data
input_df <- read.csv("screened data.csv")

# make some variable names more transparent
cleaned_df <- input_df %>%
  dplyr::mutate(participant = as.numeric(participant),
                block_n = as.numeric(block_n),
                trial_n = as.numeric(trial_n),
                accuracy = as.numeric(accuracy),
                rt = as.numeric(rt), 
                response = as.character(response))

```


```{r}


###########################################################################
# wide data
###########################################################################


# missing data ---------------------------------------------------------------------------------


missing_df <- cleaned_df %>%
  select(participant, complete) %>%
  distinct(participant, .keep_all = TRUE)


# demographics and parameters  --------------------------------------------


demo_temp_1_df <-
  cleaned_df %>%
  dplyr::group_by(participant) %>%
  dplyr::filter(grepl("demographics", task),
                item == "age") %>%  # filter rows where the task includes string
  dplyr::rename(age = response) %>%
  dplyr::mutate(age = as.numeric(age)) %>%
  dplyr::select(participant, age) %>% # select only necessary columns
  dplyr::distinct(participant, .keep_all = TRUE)

demographics_df <- cleaned_df %>%
  dplyr::group_by(participant) %>%
  dplyr::filter(grepl("demographics", task),
                item == "gender") %>%  # filter rows where the task includes string
  dplyr::rename(gender = response) %>%
  dplyr::select(participant, gender) %>% # select only necessary columns
  dplyr::distinct(participant, .keep_all = TRUE) %>%
  dplyr::mutate(gender = tolower(gender),  # homogenise gender categories. first make lower case
                gender = ifelse(gender == "f", "female",  # then convert abbreviations
                                ifelse(gender == "m", "male", gender))) %>%
  dplyr::left_join(demo_temp_1_df, by = "participant")


# ratings -----------------------------------------------------------------


ratings_df <-
  cleaned_df %>%
  dplyr::filter(grepl("ratings", task)) %>%  # filter rows where the item includes string
  dplyr::rename(ratings = response) %>%
  dplyr::select(participant, ratings) %>%
  dplyr::mutate(ratings = as.numeric(ratings)) %>%
  dplyr::group_by(participant) %>%
  dplyr::summarize(mean_rating = round(mean(ratings), 2))


# modern racism scale -----------------------------------------------------


racism_scale_df <-
  cleaned_df %>%
  dplyr::filter(grepl("racism_scale", task)) %>%  # filter rows where the item includes string
  dplyr::select(participant, response) %>%
  dplyr::group_by(participant) %>%
  dplyr::mutate(response = as.integer(response)) %>%
  dplyr::summarize(modern_racism_scale_total = sum(response))


# IAT summary scores ------------------------------------------------------


IAT_summary_stats_df <- 
  cleaned_df %>%
  dplyr::filter(task == "compatibletest1" | 
                  task == "compatibletest2" | 
                  task == "incompatibletest1" |
                  task == "incompatibletest2") %>% # test blocks only
  dplyr::mutate(IAT_too_fast_trial = ifelse(rt < 300, 1, 0)) %>%
  dplyr::group_by(participant) %>%
  dplyr::summarize(IAT_mean_RT = round(mean(rt), 0),
                   IAT_perc_acc = round(sum(accuracy)/n(), 2),
                   IAT_percent_fast_trials = sum(IAT_too_fast_trial)/n()) %>%  # arbitrary number of test block trials
  dplyr::mutate(IAT_exclude_based_on_fast_trials = ifelse(IAT_percent_fast_trials < 0.1, FALSE, TRUE)) %>%  
  dplyr::select(participant,
                IAT_mean_RT,
                IAT_perc_acc,
                IAT_exclude_based_on_fast_trials)


# shooter task --------------------------------------------------------

# trials with a non response are excluded. as such, less than 80 trials in the processed data represents some degree of non responding.

# select relevant data
shooter_trimmed <- cleaned_df %>%
  dplyr::filter(str_detect(task, "POD")) %>%  # only shooter trials
  dplyr::filter(!str_detect(task, "practice")) %>% # only non practice trials
  dplyr::select(participant, item, accuracy, response_categorisation, rt) %>%  # only vars of interest

  # filter(response_categorisation != "" &                   # exclude trials with no response
  #          response_categorisation != "Noresponse") %>%    # exclude practice block trials, which do not record a response type

  # old code (above) mixed up how practice blocks should be excluded. this is corrected above (!str_detect) and below:

  filter(response_categorisation != "Noresponse") %>%    # exclude trials with a non response
           
  # classify the trial types
  mutate(item = as.character(item),
         trial_type = ifelse(str_detect(item, "Gun"), "gun", 
                      ifelse(str_detect(item, "Object"), "object", NA)))

# total trials per participant per trial type
temp1 <- shooter_trimmed %>%
  dplyr::count(participant, trial_type) %>%
  dplyr::rename(totaltrials = n)

# n trials per participant per trial type per response type
temp2 <- shooter_trimmed %>%
  dplyr::count(participant, trial_type, response_categorisation) %>%
  dplyr::rename(ntrials = n)

shooter_data_df <- 
  # join dfs
  left_join(temp1, temp2, by = c("participant", "trial_type")) %>%
  # calculate percentages
  mutate(percentage = ntrials/totaltrials) %>%
  # reshape
  spread(response_categorisation, percentage) %>%
  dplyr::rename(percentage.Hit  = Hit, 
                percentage.Miss = Miss, 
                percentage.FA   = FA, 
                percentage.CR   = CR) %>%
  mutate(
    # add zeros where data NAs are present
    percentage.Hit   = ifelse(is.na(percentage.Hit),  0, percentage.Hit),
    percentage.Miss  = ifelse(is.na(percentage.Miss), 0, percentage.Miss),
    percentage.FA    = ifelse(is.na(percentage.FA),   0, percentage.FA),
    percentage.CR    = ifelse(is.na(percentage.CR),   0, percentage.CR)
  ) %>%
  
  group_by(participant, trial_type) %>%
  dplyr::summarize(totaltrials     = sum(ntrials,         na.rm = TRUE),
                   percentage.Hit  = sum(percentage.Hit,  na.rm = TRUE), 
                   percentage.Miss = sum(percentage.Miss, na.rm = TRUE), 
                   percentage.FA   = sum(percentage.FA,   na.rm = TRUE), 
                   percentage.CR   = sum(percentage.CR,   na.rm = TRUE)) %>%
  
  rowwise() %>%
  mutate(
    # invert Hits
    percentage.Hit = ifelse(trial_type == "Gun" & percentage.Hit == 1,
                            (1-(1/(2*totaltrials))),
                            percentage.Hit),
    
    # invert FAs
    percentage.FA = ifelse(trial_type == "Object" & percentage.FA == 0,
                           (1/(2*totaltrials)),
                           percentage.FA)
  ) %>%
  ungroup() %>%
  
  # summarize across trial types
  group_by(participant) %>%
  dplyr::summarise(percentage.Hit = sum(percentage.Hit), 
                   percentage.FA  = sum(percentage.FA)) %>%
  
  # compute d' and c
  # d' and c require values of Hit and FA other than zero and 1. Where values of 0 occur, set to 1/2N, where N = number of trials. Where values of 1 1-1/2N. Here N = 80.
  mutate(percentage.Hit = ifelse(percentage.Hit == 0, 1/(80*2), 
                                 ifelse(percentage.Hit == 1, 1-1/(80*2), percentage.Hit)),  
         percentage.FA = ifelse(percentage.FA == 0, 1/(80*2), 
                                ifelse(percentage.FA == 1, 1-1/(80*2), percentage.FA)),
         d              = round(qnorm(percentage.Hit) - qnorm(percentage.FA), 3),
         c              = round(-0.5*(qnorm(percentage.Hit) + qnorm(percentage.FA)), 3)) %>%
  mutate(percentage.Hit = round(percentage.Hit, 3),
         percentage.FA  = round(percentage.FA, 3))


shooter_summary_stats_df <- shooter_trimmed %>%
  dplyr::group_by(participant) %>%
  dplyr::summarize(n_trials_with_responses = n(),
                   shooter_mean_RT = round(mean(rt), 0),
                   shooter_perc_acc = round(sum(accuracy)/n(), 2)) %>%
  dplyr::select(participant,
                shooter_mean_RT,
                shooter_perc_acc,
                n_trials_with_responses)


# shooter bias by parcel 1 ------

# select relevant data
shooter_trimmed_parcel_1 <- cleaned_df %>%
  dplyr::filter(str_detect(task, "POD") &
                  !str_detect(task, "practice")) %>%
  group_by(participant) %>%
  dplyr::mutate(trial_n = row_number()) %>%
  ungroup() %>%
  dplyr::filter(trial_n <= 20) %>% 
  dplyr::select(participant, item, accuracy, response_categorisation, rt) %>%  # only vars of interest

  # filter(response_categorisation != "" &                   # exclude trials with no response
  #          response_categorisation != "Noresponse") %>%    # exclude practice block trials, which do not record a response type

  # old code (above) mixed up how practice blocks should be excluded. this is corrected above (!str_detect) and below:

  filter(response_categorisation != "Noresponse") %>%    # exclude trials with a non response
           
  # classify the trial types
  mutate(item = as.character(item),
         trial_type = ifelse(str_detect(item, "Gun"), "gun", 
                      ifelse(str_detect(item, "Object"), "object", NA)))

# total trials per participant per trial type
temp1_parcel_1 <- shooter_trimmed_parcel_1 %>%
  dplyr::count(participant, trial_type) %>%
  dplyr::rename(totaltrials = n)

# n trials per participant per trial type per response type
temp2_parcel_1 <- shooter_trimmed_parcel_1 %>%
  dplyr::count(participant, trial_type, response_categorisation) %>%
  dplyr::rename(ntrials = n)

shooter_data_df_parcel_1 <- 
  # join dfs
  left_join(temp1_parcel_1, temp2_parcel_1, by = c("participant", "trial_type")) %>%
  # calculate percentages
  dplyr::mutate(percentage = ntrials/totaltrials) %>%
  # reshape
  spread(response_categorisation, percentage) %>%
  dplyr::rename(percentage.Hit  = Hit, 
                percentage.Miss = Miss, 
                percentage.FA   = FA, 
                percentage.CR   = CR) %>%
  mutate(
    # add zeros where data NAs are present
    percentage.Hit   = ifelse(is.na(percentage.Hit),  0, percentage.Hit),
    percentage.Miss  = ifelse(is.na(percentage.Miss), 0, percentage.Miss),
    percentage.FA    = ifelse(is.na(percentage.FA),   0, percentage.FA),
    percentage.CR    = ifelse(is.na(percentage.CR),   0, percentage.CR)
  ) %>%
  
  group_by(participant, trial_type) %>%
  dplyr::summarize(totaltrials     = sum(ntrials,         na.rm = TRUE),
                   percentage.Hit  = sum(percentage.Hit,  na.rm = TRUE), 
                   percentage.Miss = sum(percentage.Miss, na.rm = TRUE), 
                   percentage.FA   = sum(percentage.FA,   na.rm = TRUE), 
                   percentage.CR   = sum(percentage.CR,   na.rm = TRUE)) %>%
  
  rowwise() %>%
  mutate(
    # invert Hits
    percentage.Hit = ifelse(trial_type == "Gun" & percentage.Hit == 1,
                            (1-(1/(2*totaltrials))),
                            percentage.Hit),
    
    # invert FAs
    percentage.FA = ifelse(trial_type == "Object" & percentage.FA == 0,
                           (1/(2*totaltrials)),
                           percentage.FA)
  ) %>%
  ungroup() %>%
  
  # summarize across trial types
  group_by(participant) %>%
  dplyr::summarise(percentage.Hit = sum(percentage.Hit), 
                   percentage.FA  = sum(percentage.FA)) %>%

  # compute d' and c
  # d' and c require values of Hit and FA other than zero and 1. Where values of 0 occur, set to 1/2N, where N = number of trials. Where values of 1 1-1/2N. Here N = 80.
  mutate(percentage.Hit = ifelse(percentage.Hit == 0, 1/(20*2), 
                                 ifelse(percentage.Hit == 1, 1-1/(20*2), percentage.Hit)),  
         percentage.FA  = ifelse(percentage.FA == 0, 1/(20*2), 
                                 ifelse(percentage.FA == 1, 1-1/(20*2), percentage.FA)),
         d_parcel_1     = round(qnorm(percentage.Hit) - qnorm(percentage.FA), 3)) %>%
  dplyr::select(participant, d_parcel_1)


# shooter bias by parcel 2 ------

# select relevant data
shooter_trimmed_parcel_2 <- cleaned_df %>%
  dplyr::filter(str_detect(task, "POD") &
                  !str_detect(task, "practice")) %>%
  group_by(participant) %>%
  dplyr::mutate(trial_n = row_number()) %>%
  ungroup() %>%
  dplyr::filter(trial_n > 20 & trial_n <= 40) %>% 
  dplyr::select(participant, item, accuracy, response_categorisation, rt) %>%  # only vars of interest

  # filter(response_categorisation != "" &                   # exclude trials with no response
  #          response_categorisation != "Noresponse") %>%    # exclude practice block trials, which do not record a response type

  # old code (above) mixed up how practice blocks should be excluded. this is corrected above (!str_detect) and below:

  filter(response_categorisation != "Noresponse") %>%    # exclude trials with a non response
           
  # classify the trial types
  mutate(item = as.character(item),
         trial_type = ifelse(str_detect(item, "Gun"), "gun", 
                      ifelse(str_detect(item, "Object"), "object", NA)))

# total trials per participant per trial type
temp1_parcel_2 <- shooter_trimmed_parcel_2 %>%
  dplyr::count(participant, trial_type) %>%
  dplyr::rename(totaltrials = n)

# n trials per participant per trial type per response type
temp2_parcel_2 <- shooter_trimmed_parcel_2 %>%
  dplyr::count(participant, trial_type, response_categorisation) %>%
  dplyr::rename(ntrials = n)

shooter_data_df_parcel_2 <- 
  # join dfs
  left_join(temp1_parcel_2, temp2_parcel_2, by = c("participant", "trial_type")) %>%
  # calculate percentages
  dplyr::mutate(percentage = ntrials/totaltrials) %>%
  # reshape
  spread(response_categorisation, percentage) %>%
  dplyr::rename(percentage.Hit  = Hit, 
                percentage.Miss = Miss, 
                percentage.FA   = FA, 
                percentage.CR   = CR) %>%
  mutate(
    # add zeros where data NAs are present
    percentage.Hit   = ifelse(is.na(percentage.Hit),  0, percentage.Hit),
    percentage.Miss  = ifelse(is.na(percentage.Miss), 0, percentage.Miss),
    percentage.FA    = ifelse(is.na(percentage.FA),   0, percentage.FA),
    percentage.CR    = ifelse(is.na(percentage.CR),   0, percentage.CR)
  ) %>%
  
  group_by(participant, trial_type) %>%
  dplyr::summarize(totaltrials     = sum(ntrials,         na.rm = TRUE),
                   percentage.Hit  = sum(percentage.Hit,  na.rm = TRUE), 
                   percentage.Miss = sum(percentage.Miss, na.rm = TRUE), 
                   percentage.FA   = sum(percentage.FA,   na.rm = TRUE), 
                   percentage.CR   = sum(percentage.CR,   na.rm = TRUE)) %>%
  
  rowwise() %>%
  mutate(
    # invert Hits
    percentage.Hit = ifelse(trial_type == "Gun" & percentage.Hit == 1,
                            (1-(1/(2*totaltrials))),
                            percentage.Hit),
    
    # invert FAs
    percentage.FA = ifelse(trial_type == "Object" & percentage.FA == 0,
                           (1/(2*totaltrials)),
                           percentage.FA)
  ) %>%
  ungroup() %>%
  
  # summarize across trial types
  group_by(participant) %>%
  dplyr::summarise(percentage.Hit = sum(percentage.Hit), 
                   percentage.FA  = sum(percentage.FA)) %>%

  # compute d' and c
  # d' and c require values of Hit and FA other than zero and 1. Where values of 0 occur, set to 1/2N, where N = number of trials. Where values of 1 1-1/2N. Here N = 80.
  mutate(percentage.Hit = ifelse(percentage.Hit == 0, 1/(20*2), 
                                 ifelse(percentage.Hit == 1, 1-1/(20*2), percentage.Hit)),  
         percentage.FA  = ifelse(percentage.FA == 0, 1/(20*2), 
                                 ifelse(percentage.FA == 1, 1-1/(20*2), percentage.FA)),
         d_parcel_2     = round(qnorm(percentage.Hit) - qnorm(percentage.FA), 3)) %>%
  dplyr::select(participant, d_parcel_2)


# shooter bias by parcel 3 ------

# select relevant data
shooter_trimmed_parcel_3 <- cleaned_df %>%
  dplyr::filter(str_detect(task, "POD") &
                  !str_detect(task, "practice")) %>%
  group_by(participant) %>%
  dplyr::mutate(trial_n = row_number()) %>%
  ungroup() %>%
  dplyr::filter(trial_n > 40 & trial_n <= 60) %>% 
  dplyr::select(participant, item, accuracy, response_categorisation, rt) %>%  # only vars of interest

  # filter(response_categorisation != "" &                   # exclude trials with no response
  #          response_categorisation != "Noresponse") %>%    # exclude practice block trials, which do not record a response type

  # old code (above) mixed up how practice blocks should be excluded. this is corrected above (!str_detect) and below:

  filter(response_categorisation != "Noresponse") %>%    # exclude trials with a non response
           
  # classify the trial types
  mutate(item = as.character(item),
         trial_type = ifelse(str_detect(item, "Gun"), "gun", 
                      ifelse(str_detect(item, "Object"), "object", NA)))

# total trials per participant per trial type
temp1_parcel_3 <- shooter_trimmed_parcel_3 %>%
  dplyr::count(participant, trial_type) %>%
  dplyr::rename(totaltrials = n)

# n trials per participant per trial type per response type
temp2_parcel_3 <- shooter_trimmed_parcel_3 %>%
  dplyr::count(participant, trial_type, response_categorisation) %>%
  dplyr::rename(ntrials = n)

shooter_data_df_parcel_3 <- 
  # join dfs
  left_join(temp1_parcel_3, temp2_parcel_3, by = c("participant", "trial_type")) %>%
  # calculate percentages
  dplyr::mutate(percentage = ntrials/totaltrials) %>%
  # reshape
  spread(response_categorisation, percentage) %>%
  dplyr::rename(percentage.Hit  = Hit, 
                percentage.Miss = Miss, 
                percentage.FA   = FA, 
                percentage.CR   = CR) %>%
  mutate(
    # add zeros where data NAs are present
    percentage.Hit   = ifelse(is.na(percentage.Hit),  0, percentage.Hit),
    percentage.Miss  = ifelse(is.na(percentage.Miss), 0, percentage.Miss),
    percentage.FA    = ifelse(is.na(percentage.FA),   0, percentage.FA),
    percentage.CR    = ifelse(is.na(percentage.CR),   0, percentage.CR)
  ) %>%
  
  group_by(participant, trial_type) %>%
  dplyr::summarize(totaltrials     = sum(ntrials,         na.rm = TRUE),
                   percentage.Hit  = sum(percentage.Hit,  na.rm = TRUE), 
                   percentage.Miss = sum(percentage.Miss, na.rm = TRUE), 
                   percentage.FA   = sum(percentage.FA,   na.rm = TRUE), 
                   percentage.CR   = sum(percentage.CR,   na.rm = TRUE)) %>%
  
  rowwise() %>%
  mutate(
    # invert Hits
    percentage.Hit = ifelse(trial_type == "Gun" & percentage.Hit == 1,
                            (1-(1/(2*totaltrials))),
                            percentage.Hit),
    
    # invert FAs
    percentage.FA = ifelse(trial_type == "Object" & percentage.FA == 0,
                           (1/(2*totaltrials)),
                           percentage.FA)
  ) %>%
  ungroup() %>%
  
  # summarize across trial types
  group_by(participant) %>%
  dplyr::summarise(percentage.Hit = sum(percentage.Hit), 
                   percentage.FA  = sum(percentage.FA)) %>%

  # compute d' and c
  # d' and c require values of Hit and FA other than zero and 1. Where values of 0 occur, set to 1/2N, where N = number of trials. Where values of 1 1-1/2N. Here N = 80.
  mutate(percentage.Hit = ifelse(percentage.Hit == 0, 1/(20*2), 
                                 ifelse(percentage.Hit == 1, 1-1/(20*2), percentage.Hit)),  
         percentage.FA  = ifelse(percentage.FA == 0, 1/(20*2), 
                                 ifelse(percentage.FA == 1, 1-1/(20*2), percentage.FA)),
         d_parcel_3     = round(qnorm(percentage.Hit) - qnorm(percentage.FA), 3)) %>%
  dplyr::select(participant, d_parcel_3)



# shooter bias by parcel 4 ------

# select relevant data
shooter_trimmed_parcel_4 <- cleaned_df %>%
  dplyr::filter(str_detect(task, "POD") &
                  !str_detect(task, "practice")) %>%
  group_by(participant) %>%
  dplyr::mutate(trial_n = row_number()) %>%
  ungroup() %>%
  dplyr::filter(trial_n > 60) %>% 
  dplyr::select(participant, item, accuracy, response_categorisation, rt) %>%  # only vars of interest

  # filter(response_categorisation != "" &                   # exclude trials with no response
  #          response_categorisation != "Noresponse") %>%    # exclude practice block trials, which do not record a response type

  # old code (above) mixed up how practice blocks should be excluded. this is corrected above (!str_detect) and below:

  filter(response_categorisation != "Noresponse") %>%    # exclude trials with a non response
           
  # classify the trial types
  mutate(item = as.character(item),
         trial_type = ifelse(str_detect(item, "Gun"), "gun", 
                      ifelse(str_detect(item, "Object"), "object", NA)))

# total trials per participant per trial type
temp1_parcel_4 <- shooter_trimmed_parcel_4 %>%
  dplyr::count(participant, trial_type) %>%
  dplyr::rename(totaltrials = n)

# n trials per participant per trial type per response type
temp2_parcel_4 <- shooter_trimmed_parcel_4 %>%
  dplyr::count(participant, trial_type, response_categorisation) %>%
  dplyr::rename(ntrials = n)

shooter_data_df_parcel_4 <- 
  # join dfs
  left_join(temp1_parcel_4, temp2_parcel_4, by = c("participant", "trial_type")) %>%
  # calculate percentages
  dplyr::mutate(percentage = ntrials/totaltrials) %>%
  # reshape
  spread(response_categorisation, percentage) %>%
  dplyr::rename(percentage.Hit  = Hit, 
                percentage.Miss = Miss, 
                percentage.FA   = FA, 
                percentage.CR   = CR) %>%
  mutate(
    # add zeros where data NAs are present
    percentage.Hit   = ifelse(is.na(percentage.Hit),  0, percentage.Hit),
    percentage.Miss  = ifelse(is.na(percentage.Miss), 0, percentage.Miss),
    percentage.FA    = ifelse(is.na(percentage.FA),   0, percentage.FA),
    percentage.CR    = ifelse(is.na(percentage.CR),   0, percentage.CR)
  ) %>%
  
  group_by(participant, trial_type) %>%
  dplyr::summarize(totaltrials     = sum(ntrials,         na.rm = TRUE),
                   percentage.Hit  = sum(percentage.Hit,  na.rm = TRUE), 
                   percentage.Miss = sum(percentage.Miss, na.rm = TRUE), 
                   percentage.FA   = sum(percentage.FA,   na.rm = TRUE), 
                   percentage.CR   = sum(percentage.CR,   na.rm = TRUE)) %>%
  
  rowwise() %>%
  mutate(
    # invert Hits
    percentage.Hit = ifelse(trial_type == "Gun" & percentage.Hit == 1,
                            (1-(1/(2*totaltrials))),
                            percentage.Hit),
    
    # invert FAs
    percentage.FA = ifelse(trial_type == "Object" & percentage.FA == 0,
                           (1/(2*totaltrials)),
                           percentage.FA)
  ) %>%
  ungroup() %>%
  
  # summarize across trial types
  group_by(participant) %>%
  dplyr::summarise(percentage.Hit = sum(percentage.Hit), 
                   percentage.FA  = sum(percentage.FA)) %>%

  # compute d' and c
  # d' and c require values of Hit and FA other than zero and 1. Where values of 0 occur, set to 1/2N, where N = number of trials. Where values of 1 1-1/2N. Here N = 80.
  mutate(percentage.Hit = ifelse(percentage.Hit == 0, 1/(20*2), 
                                 ifelse(percentage.Hit == 1, 1-1/(20*2), percentage.Hit)),  
         percentage.FA  = ifelse(percentage.FA == 0, 1/(20*2), 
                                 ifelse(percentage.FA == 1, 1-1/(20*2), percentage.FA)),
         d_parcel_4     = round(qnorm(percentage.Hit) - qnorm(percentage.FA), 3)) %>%
  dplyr::select(participant, d_parcel_4)


shooter_parcels <- shooter_data_df_parcel_1 %>%
  full_join(shooter_data_df_parcel_2, by = "participant") %>%
  full_join(shooter_data_df_parcel_3, by = "participant") %>%
  full_join(shooter_data_df_parcel_4, by = "participant")


# join wide D1 scored data and write to disk ------------------------------


wide_data_df <- 
  plyr::join_all(list(as.data.frame(missing_df),
                      as.data.frame(demographics_df),  # join_all throws a requires input be data.frame error, despite is.data.frame returning TRUE for all members of list. Workaround is to coerce all to DF here. 
                      as.data.frame(racism_scale_df),
                      as.data.frame(ratings_df),
                      as.data.frame(IAT_summary_stats_df),
                      as.data.frame(shooter_data_df),
                      as.data.frame(shooter_parcels),
                      as.data.frame(shooter_summary_stats_df)),
                 by = "participant",
                 type = "full") %>%
  dplyr::arrange(participant) %>%
  dplyr::mutate(exclude = ifelse(IAT_exclude_based_on_fast_trials == FALSE & complete == TRUE, FALSE, TRUE)) %>%
  dplyr::group_by(participant) %>%
  dplyr::mutate(condition = participant %% 8,
                condition = ifelse(condition == 0, 8, condition),  # convert participant codes to conditions and correct modulus%%8==0 to condition=8
                IAT_condition = ifelse(condition <= 4, "Race IAT", "Flowers-Insects IAT"),
                block_order = ifelse(condition %% 2 == 1, "congruent", "incongruent"),
                task_order = ifelse(condition == 1 | condition == 2 | condition == 5 | condition == 6,
                                    "ratings first", "SCIAT first")) %>%
  ungroup()


# print N
wide_data_df %>% dplyr::count(IAT_condition, exclude)

wide_data_df %>% write.csv(file = "processed/processed summary data - wide format.csv", row.names = FALSE)


###########################################################################
# long format data on raw rts/ratings from here
###########################################################################


# other tasks -------------------------------------------------------------


other_tasks_df <- wide_data_df %>%
  dplyr::select(participant, IAT_condition, block_order, 
                task_order, 
                gender, 
                age, 
                modern_racism_scale_total, 
                IAT_exclude_based_on_fast_trials)


# long format shooter rts --------------------------------------------------


shooter_trimmed %>% 
  dplyr::left_join(other_tasks_df, by = "participant") %>%
  write.csv(file = "processed/processed shooter task data - long format.csv", row.names = FALSE)


# long format ratings rts -------------------------------------------------


ratings_long_format_df <- cleaned_df %>%
  dplyr::filter(task == "ratings") %>%
  dplyr::mutate(rating = as.integer(response)) %>%
  dplyr::select(participant, 
                trial_n,
                rating,
                self_report_item) %>%
  dplyr::left_join(other_tasks_df, by = "participant")

ratings_long_format_df %>% write.csv(file = "processed/processed ratings data - long format.csv", row.names = FALSE)

```